on: [push, pull_request]
name: linter

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: 1.60.3
        only-new-issues: true
        args: --verbose